// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJplB0fti9ZRASyx_Yez0Vbgfd53xTPAU',
    appId: '1:656079256305:web:c893bb51a27b2049f70750',
    messagingSenderId: '656079256305',
    projectId: 'fitness-coach-app-5b7b5',
    authDomain: 'fitness-coach-app-5b7b5.firebaseapp.com',
    storageBucket: 'fitness-coach-app-5b7b5.appspot.com',
    measurementId: 'G-3FJGV1MBVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1GRCv9hMil3ddZjvEDK5K-UakMYsfNs0',
    appId: '1:656079256305:android:f7b3e4e8fe9b924cf70750',
    messagingSenderId: '656079256305',
    projectId: 'fitness-coach-app-5b7b5',
    storageBucket: 'fitness-coach-app-5b7b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60LKHuiJtIuQ-okkvhm72sp3KZ2sCkYo',
    appId: '1:656079256305:ios:3fea7fde451ca142f70750',
    messagingSenderId: '656079256305',
    projectId: 'fitness-coach-app-5b7b5',
    storageBucket: 'fitness-coach-app-5b7b5.appspot.com',
    iosBundleId: 'com.example.leapReadTranslateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60LKHuiJtIuQ-okkvhm72sp3KZ2sCkYo',
    appId: '1:656079256305:ios:3fea7fde451ca142f70750',
    messagingSenderId: '656079256305',
    projectId: 'fitness-coach-app-5b7b5',
    storageBucket: 'fitness-coach-app-5b7b5.appspot.com',
    iosBundleId: 'com.example.leapReadTranslateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJplB0fti9ZRASyx_Yez0Vbgfd53xTPAU',
    appId: '1:656079256305:web:a4deb010ec2235bcf70750',
    messagingSenderId: '656079256305',
    projectId: 'fitness-coach-app-5b7b5',
    authDomain: 'fitness-coach-app-5b7b5.firebaseapp.com',
    storageBucket: 'fitness-coach-app-5b7b5.appspot.com',
    measurementId: 'G-L0YD74PDLK',
  );

}